version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1
  macos: circleci/macos@2.3.4

executors:
  gen2_medium:
    macos:
      xcode: 14.3.1
    resource_class: macos.x86.medium.gen2
  m1_medium:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.medium.gen1
  m1_large:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.large.gen1

jobs:
  unit_test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    parallelism: 2
    steps:
      - macos/preboot-simulator:
          device: iPhone 14
          version: '16.4'
      - checkout
      - run: git submodule update --init --recursive
      - ruby/install-deps
      - run: bundle exec fastlane unit_tests
      - run:
        name: Split tests and run UITests
        command: |
          CLASSNAMES=$(circleci tests glob "Fastfile" \
          | sed 's@/@.@g' \
          | sed 's/.swift//' \
          | circleci tests split --split-by=timings --timings-type=classname)
          FASTLANE_ARGS=$(echo $CLASSNAMES | sed -e 's/\./\//g' -e 's/ /,/g')
          bundle exec fastlane ui_test_without_building tests:$FASTLANE_ARGS
      - store_test_results:
          path: fastlane/report.xml

  integration_test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - macos/preboot-simulator:
          device: iPhone 14
          version: '16.4'
      - checkout
      - run: git submodule update --init --recursive
      - ruby/install-deps
      - run: bundle exec fastlane integration_tests
      - run: bundle exec fastlane atb_uitests
      - store_test_results:
          path: fastlane/report.xml

workflows:
  gen2_medium_workflow:
    jobs:
      - unit_test:
          executor: gen2_medium
      - integration_test:
          executor: gen2_medium
  m1_medium_workflow:
    jobs:
      - unit_test:
          executor: m1_medium
      - integration_test:
          executor: m1_medium
  m1_large_workflow:
    jobs:
      - unit_test:
          executor: m1_large
      - integration_test:
          executor: m1_large
